import { useState } from 'react';
import Card from '../components/Card';
import Loader from '../components/Loader';
import FormField from '../components/FormField';
import RenderCards from '../components/RenderCards';

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchInput, setSearchInput] = useState('');
  return (
    <div className="w-[95%] py-3 mx-auto">
      <section className="mx-auto max-w-7xl">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
            Browse through a collection of imaginative and visually stunning
            images generated by DALL-E AI
          </p>
        </div>
        <div className="mt-10">
          <FormField />
        </div>
        <div className="mt-10">
          {loading ? (
            <div className="flex items-center justify-center">
              <Loader />
            </div>
          ) : (
            <>
              {searchInput && (
                <h2 className="mb-3 text-xl font-medium">
                  Showing results for{' '}
                  <span className="text-green-700">{searchInput}</span>
                </h2>
              )}
              <div className="grid grid-cols-1 gap-3 lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2">
                {searchInput ? (
                  <RenderCards data={[]} title="No search results found" />
                ) : (
                  <RenderCards data={[]} title="No post found" />
                )}
              </div>
            </>
          )}
        </div>
      </section>
    </div>
  );
};

export default Home;
